export const products = [
    {
      name: "IKEA Ultrabook Laptop",
      price: 1200,
      description: "A sleek ultrabook with a 14-inch Retina display, Intel i7 processor, 16GB RAM, and 512GB SSD.",
      image: "../public/uploads/laptop1.jpeg",
      company: "ikea",
    },
    {
      name: "Liddy Budget Smartphone",
      price: 350,
      description: "A budget-friendly smartphone with a 6.5-inch FHD display, 4GB RAM, and 64GB storage.",
      image: "../public/uploads/mobile1.jpeg",
      company: "liddy",
    },
    {
      name: "Caressa Gaming Laptop",
      price: 1500,
      description: "High-performance gaming laptop with RTX 3060 GPU, 16GB RAM, and 1TB NVMe SSD.",
      image: "../public/uploads/laptop2.jpeg",
      company: "caressa",
    },
    {
      name: "Marcos Foldable Smartphone",
      price: 2000,
      description: "Innovative foldable smartphone with a 7.6-inch AMOLED display, 12GB RAM, and 256GB storage.",
      image: "../public/uploads/mobile2.jpeg",
      company: "marcos",
    },
    {
      name: "IKEA Office Laptop",
      price: 900,
      description: "A lightweight office laptop with a 13.3-inch FHD display, Intel i5 processor, and 8GB RAM.",
      image: "../public/uploads/laptop3.jpeg",
      company: "ikea",
    },
    {
      name: "Liddy Compact Smartphone",
      price: 299,
      description: "Compact smartphone with a 5.8-inch display, 3GB RAM, and 32GB internal storage.",
      image: "../public/uploads/mobile3.jpeg",
      company: "liddy",
    },
    {
      name: "Caressa Creator Laptop",
      price: 1800,
      description: "A laptop designed for creators with 4K OLED display, 32GB RAM, and 1TB SSD storage.",
      image: "../public/uploads/laptop4.jpeg",
      company: "caressa",
    },
    {
      name: "Marcos Premium Smartphone",
      price: 1200,
      description: "Flagship smartphone with Snapdragon 8 Gen 2, 12GB RAM, and 512GB storage.",
      image: "../public/uploads/mobile4.jpeg",
      company: "marcos",
    },
    {
      name: "IKEA Student Laptop",
      price: 650,
      description: "Affordable student laptop with 15.6-inch FHD display, 8GB RAM, and 256GB SSD.",
      image: "../public/uploads/laptop5.jpeg",
      company: "ikea",
    },
    {
      name: "Liddy Dual Camera Smartphone",
      price: 399,
      description: "Smartphone with dual cameras, 48MP main lens, 6GB RAM, and 128GB storage.",
      image: "../public/uploads/mobile5.jpeg",
      company: "liddy",
    },
    {
      name: "Caressa Workstation Laptop",
      price: 2200,
      description: "A workstation laptop with NVIDIA Quadro GPU, 64GB RAM, and Xeon processor.",
      image: "../public/uploads/laptop6.jpeg",
      company: "caressa",
    },
    {
      name: "Marcos 5G Smartphone",
      price: 1100,
      description: "5G-enabled smartphone with a 6.7-inch AMOLED display and 256GB storage.",
      image: "../public/uploads/mobile6.jpeg",
      company: "marcos",
    },
    {
      name: "IKEA All-Rounder Laptop",
      price: 850,
      description: "A versatile laptop with Intel i5, 8GB RAM, and 512GB SSD for everyday use.",
      image: "../public/uploads/laptop7.jpeg",
      company: "ikea",
    },
    {
      name: "Liddy Photography Smartphone",
      price: 899,
      description: "High-end smartphone for photography enthusiasts with 108MP primary camera.",
      image: "../public/uploads/mobile7.jpeg",
      company: "liddy",
    },
    {
      name: "Caressa Convertible Laptop",
      price: 1200,
      description: "2-in-1 convertible laptop with touchscreen and stylus support for creators.",
      image: "../public/uploads/laptop8.jpeg",
      company: "caressa",
    },
    {
      name: "Marcos Rugged Smartphone",
      price: 499,
      description: "Durable smartphone with IP68 rating, 8GB RAM, and 128GB storage.",
      image: "../public/uploads/mobile8.jpeg",
      company: "marcos",
    },
    {
      name: "IKEA Chromebook",
      price: 400,
      description: "Lightweight Chromebook with 12.5-inch display, 4GB RAM, and 64GB eMMC.",
      image: "../public/uploads/laptop9.jpeg",
      company: "ikea",
    },
    {
      name: "Liddy Pro Smartphone",
      price: 599,
      description: "Mid-range smartphone with MediaTek Dimensity 1200, 8GB RAM, and 128GB storage.",
      image: "../public/uploads/mobile9.jpeg",
      company: "liddy",
    },
    {
      name: "Caressa Lightweight Laptop",
      price: 700,
      description: "Portable laptop with a 13-inch FHD display, 8GB RAM, and 256GB SSD.",
      image: "../public/uploads/laptop10.jpeg",
      company: "caressa",
    },
    {
      name: "Marcos Mini Smartphone",
      price: 449,
      description: "Compact smartphone with high performance, 5.4-inch display, and 128GB storage.",
      image: "../public/uploads/mobile10.jpeg",
      company: "marcos",
    },
];